### ISSUE TITLE
Panel content fills only half the available space

### ISSUE THREAD

**Issue by sandnath** [rpocklin/angular-timeline#35]
Hello,
First of all - great work and I loved this. Just one issue for now... How do I fill up the whole content with text? It always only fills half of it - does not matter html content or simple text.

What changes need to be done in css or any other place to achieve this?

Here is a picture
![tl-1](https://cloud.githubusercontent.com/assets/20116364/17191109/5fb51812-53fd-11e6-8649-cda3e7d789cd.png)
...

**Comment by rpocklin** [comment]
Thanks for the picture, so much easier to understand than describing it.

You decide what content goes in the timeline event, there's no requirement to limit yourself to the directive I wrote.  Likewise you can go for it with the CSS to maximise the space.  I could possibly add a `class="fluid"` option to make it expand to fill the container, if others would like it too.

**Comment by sandnath** [comment]
Thanks so much for the response. Can you please elaborate with little bit more code? I am not too conversant with css but I can hack better if you please help. Appreciate it!

**Comment by rpocklin** [comment]
I have fixed this in master, I will release it soon.

**Comment by pdemilly** [comment]
I just tried it with master and it is still not filling the whole width and the timeline icons are not lining up with the edge when using either right or left. Any suggestion on how to remove that unused space.

Thanks

**Comment by bentrm** [comment]
Using class names instead of the directives tag names in the stylesheets fixed this for me. Pretty much the same changes that are suggested in #36.
